apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ervg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oswt-tenant/rhtap-demo-app/hacbs-test-project-ervg@sha256:d5eca297384c953ad4782214e9a1ebce7537f8cfc5c143418b9a52a143779ae1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
